### ISSUE TITLE
screener - TEXT: Have you ever been in removal proceedings y/n details - mimic what's on the I-821 form questions (32-36) - No need to loop proceedings since most are recent arrivals and will have just 1 proceeding

### ISSUE THREAD

**Issue by nonprofittechy** [IllinoisLegalAidOnline/docassemble-USCISApplications#126]

**Comment by mnewsted** [comment]
@nonprofittechy I think this might have been addressed already?

**Comment by mnewsted** [comment]
@nonprofittechy I encountered some issues when I did testing on this the morning of 2/27.

The interview no longer loops when asking for removal proceedings, so that work has been done. (I still see the code, but it appears to have been overwritten by id: immigration proceedings).

This issue seems to be requesting that we ask the full removal proceedings questions in the screener as we do in the application. If so, maybe we could pass that information along to the application so it doesn't need to be asked again? Or just defaulted? If these questions are expanded, I think the screener doc might also need to be adjusted to accommodate the different fields.

2 possible issues:
1) There may be an issue in relating the type of proceeding to the location questions. The show if logic in id: immigration proceedings looks like there isn't a full enforcement of these location rules.
Proceeding type:
33a - Immigration Court
33b - Board of Immigration Appeals (BIA)
33c - no longer in DOJ or DHS, but in Fed court
Proceeding location:
34 - location of DOJ or DHS proceedings (should only appear if 33a or 33b selected)
35 - location of fed court proceedings (should only appear if 33c is selected)

2) For users[1] and following, who are minors, it appears that most of the information is carried over from users[0]. However, the proceeding type (Immigration court, BIA, or fed court) checkboxes does not. Since the locations fields do carry over, shouldn't the proceeding type also default to the users[0]'s answers?

**Comment by nonprofittechy** [comment]
May want to discuss with Jane again to see if this is an edge case they're really OK leaving unhandled.

**Comment by nonprofittechy** [comment]
I think this is resolved

**Comment by mnewsted** [comment]
@nonprofittechy We think this can be closed. Agree?
