### ISSUE TITLE
Affidavit of continuous presence and in the EAD  fee waiver, add the parent's signature to the minor's forms?

### ISSUE THREAD

**Issue by nonprofittechy** [IllinoisLegalAidOnline/docassemble-USCISApplications#139]
Problem with this: we don't ask people what relationships they have. Should we add this question when there is a minor?

**Comment by aidanielson** [comment]
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/7cd46324-60cf-4439-8870-6fdcf634c134)

**Comment by mnewsted** [comment]
Matt has questions for TRP

**Comment by mnewsted** [comment]
TRP said applicants 14 and over should sign their own form. If they are under 14, use the parents signature. This led to the following discussion.

Q: Right now, we don't have any question that asks who is related to who. Should we use the signature of the first person who completes the interview? Or should we ask a question "who is this child's parent"?

J: Could we add question when they add a new family member that requests relationship? Otherwise, yes "who is this child's parent" can work
