### ISSUE TITLE
Check on countries transited through code

### ISSUE THREAD

**Issue by nonprofittechy** [IllinoisLegalAidOnline/docassemble-USCISApplications#155]
- [x] Page 7, part 7, Item 1c - not checking the box
- [x] Page 7, part 7 Items 1c-5 - not populating
- [x] Part 7 #20a and 20b - and 20c and 20d - the program forces you to answer to move on even if the answer to the underlying question is "NO"

Probably fixed in #151

**Comment by mnewsted** [comment]
@nonprofittechy @aidanielson I have some I-821 questions for you.

On Page 7, part 7 Items 1c-5, 1c-4 are not populating because we are currently sending that to an addendum.
Question 5 (Ever offered immigration status by another country that you did not accept) is not populating because if the applicant said NO to screener users[i].traveled_through_other_countries (or if users[0] said NO then others will default), then users[i].other_country_immigration_status_offered will not be set and neither box in 5 will be checked. It seems unlikely that users[0].traveled_through_other_countries will ever be NO, but it must have happened otherwise we wouldn't have received this feedback. Should I add logic to the attachment block so that it will default to No (unless applicant--users[i]-- has said YES)?

On the Have you evers 20c and 20d, these are only asked under certain conditions. 20c is asked only if 20a or 20b is YES. 20d is asked only if 20c is YES. We could try to use show if, but I'm not sure how that would work in a grid. What I think might be a better approach is to 1) Add this conditional language to the question text (in the various places where it occurs) and 2) in the attachment block add logic so that it will properly check or leave blank depending on other answers. To implement, I'd need an update on where the question text lives (I think @aidanielson is working on updating/streamlining this).

What do you think?

**Comment by aidanielson** [comment]
w/r/t the second paragraph above:

I have made this a subissue assigned to me and Matt. I agree with reformatting those questions to match the logic which I agree is as you state. There may be some effect on the downstream processing of 'Yes' answers to these questions (i.e., for every truthy value of the have-you-ever variables, go to explanation screen/box) but I'll ensure the code is in harmony with that existing downstream processing.

**Comment by mnewsted** [comment]
On the first part, @aidanielson identified that the screener questions are confusing.
  - Did you travel through Central America (Colombia, Panama, Costa Rica, Nicaragua, Honduras, Guatemala, and Mexico) before entering the US?: users[i].traveled_through_central_america
    datatype: yesnoradio
    default: |
      ${ showifdef("users[0].traveled_through_central_america") if i > 0 else '' }
  - Did you travel through other countries?: users[i].traveled_through_other_countries
    datatype: yesnoradio
    default: |
      ${ showifdef("users[0].traveled_through_other_countries") if i > 0 else '' }
  - Which countries? (list all countries, incuding those in South America, with a comma between each country): users[i].other_countries_traveled_through
    datatype: area
    show if: users[i].traveled_through_other_countries
    default: |
      ${ showifdef("users[0].countries_traveled_through") if i > 0 else '' }

Maybe the 2nd question, "Did you travel through other countries?" should be "Did you travel through other countries besides Colombia, Panama, Costa Rica, Nicaragua, Honduras, Guatemala, and Mexico?" And the 3rd question can be, "Which other countries?"

I think those above question changes and then adding an additional code to the attachment block (see below), will address the "5 not populating" issue. What do you think @nonprofittechy ?

    - "other_country_immigration_status_offered_yes": ${ True if users[i].other_country_immigration_status_offered else '' }
    - "other_country_immigration_status_offered_no": ${ True if not users[i].other_country_immigration_status_offered or users[i].users[i].traveled_through_other_countries == False else '' }

**Comment by nonprofittechy** [comment]
This sounds like a good plan

**Comment by mnewsted** [comment]
We will remove "above" and "(left)"
