### ISSUE TITLE
refactor the two conditional have-you-ever questions

### ISSUE THREAD

**Issue by aidanielson** [IllinoisLegalAidOnline/docassemble-USCISApplications#167]
On the Have you evers 20c and 20d, these are only asked under certain conditions. 20c is asked only if 20a or 20b is YES. 20d is asked only if 20c is YES. We could try to use show if, but I'm not sure how that would work in a grid. What I think might be a better approach is to 1) Add this conditional language to the question text (in the various places where it occurs) and 2) in the attachment block add logic so that it will properly check or leave blank depending on other answers. To implement, I'd need an update on where the question text lives (I think @aidanielson is working on updating/streamlining this).

**Comment by mnewsted** [comment]
@aidanielson Were you planning on working on this for the Week 1 milestone (in #155)? I think we can take the simpler path of adjusting the question text & attachment block logic rather than worrying about the question logic. See my idea from before:

"What I think might be a better approach is to 1) Add this conditional language to the question text (in the various places where it occurs) and 2) in the attachment block add logic so that it will properly check or leave blank depending on other answers."

**Comment by aidanielson** [comment]
i took the easier, more sensible path that Matt suggested. Will work on refactoring the have-you-evers this week.
