### ISSUE TITLE
Tests aren't testing download-ability

### ISSUE THREAD

**Issue by nonprofittechy** [IllinoisLegalAidOnline/docassemble-USCISApplications#242]
Just noticed that all of the tests currently just try to reach the waiting screen. That isn't going to catch a wide class of bugs.

We need to adjust so that we test being able to reach a download page, not just a waiting page.

https://github.com/IllinoisLegalAidOnline/docassemble-USCISApplications/blob/5ddc3f378e5e7410d142326b34867ebfeb78b6f1/docassemble/USCISApplications/data/sources/automatedTests.feature#L16

**Comment by nonprofittechy** [comment]
I recognize this might need some collaboration with @plocket to figure out how to update the Kiln test to work with background tasks/unknown wait time

**Comment by nonprofittechy** [comment]
See: https://assemblyline.suffolklitlab.org/docs/alkiln/writing#wait

**Comment by ll-jgraszer** [comment]
The tests will basically need a waiting period from reaching the "waiting screen" since that's the background task buffer point until the download is ready. Then after waiting a period of time TBD the process should reach the download screen. While it'll add more time to the overall testing running it should verify we're reaching the download screen.

**Comment by ll-jgraszer** [comment]
According to the docs we can also have it download the generated documents using https://assemblyline.suffolklitlab.org/docs/alkiln/writing/#download

**Comment by nonprofittechy** [comment]
FWIW, if we don't see an error, it's probably OK to skip the download step (that's more for testing that the right information is filled out, either manually by downloading the artifacts or in some automated step)
