### ISSUE TITLE
If a question has a field for a start and end date, add simple min to the latter date to ensure it never happens before. Examples are id: countries entered or traveled to before U.S. and id: immigration proceedings.

### ISSUE THREAD

**Issue by nonprofittechy** [IllinoisLegalAidOnline/docassemble-USCISApplications#29]

**Comment by nonprofittechy** [comment]
@mnewsted  I don't think this is possible when they're asked on the same screen? Are you thinking of validation code maybe?

**Comment by mnewsted** [comment]
Ah yes validation code sorry

**Comment by mnewsted** [comment]
Put this on hold until sections with dates (like travel through country start/end) are complete

**Comment by nonprofittechy** [comment]
Possible duplicate of #143

**Comment by mnewsted** [comment]
@nonprofittechy When I add the following code to id: tps_screening_questions, the validation works but the error appears as a toast pop-up rather than next to the field. I've seen this before but don't know how to force it to appear next to the field. Is there a way to do it? If not, I think it might be better not including the date validation.

`validation code: |`
`  if users[i].last_entry_date_year < users[i].date_left_home_country_year:`
`    validation_error("Year of last US entry must be after year left home country.", field=users[i].last_entry_date_year)`

**Comment by mnewsted** [comment]
I do think we can add year max at current year.

**Comment by nonprofittechy** [comment]
The field= needs to be in quotes. That should fix it

**Comment by mnewsted** [comment]
duh. how did i miss that. thanks! works perfectly now.

**Comment by mnewsted** [comment]
Some date minimums were implemented, but the dates on the screener have been adjusted so no additional validation will be used.

**Comment by mnewsted** [comment]
updated in merge to main this week.
